### ISSUE TITLE
Cache setting is missing the 'deliver' action

### ISSUE THREAD

**Issue by jsierles** [fastly/go-fastly#136]
Fastly supports 'deliver' in its UI for cache settings, so this provider should add the option as well as `cache`, `pass` and `restart`.

![Screen Shot 2019-12-05 at 12 34 53](https://user-images.githubusercontent.com/82/70232003-bc7d1c00-175b-11ea-977c-85bfd950e09d.png)

**Comment by Integralist** [comment]
Hi @jsierles thanks for opening this issue (and your patience waiting for a reply).

Upon investigating the available actions in the UI we find that the 'Deliver' option is in fact passing a value of 'cache':

<img width="437" alt="Screenshot 2021-01-06 at 13 34 20" src="https://user-images.githubusercontent.com/180050/103774081-f0440880-5023-11eb-9bc4-53f68fa46fd3.png">

Which is already supported in Go-Fastly:
https://github.com/fastly/go-fastly/blob/f435b9545d1fcad68ee3d0e942ad84da9d2792b5/fastly/cache_setting.go#L10-L19

If you have any further queries then please just let me know. I'll leave this issue open for a little longer to give you a chance to review and either close it yourself or raise questions, otherwise if there is no further discussion required by the end of the week I'll close this issue.

Thanks.
