### ISSUE TITLE
ListServices ignores all parameters

### ISSUE THREAD

**Issue by andrewbaxter** [fastly/go-fastly#332]
Additionally, upstream docs don't have any information on listing services AFAICT.

Is the assumption to make here that `/services` always returns all services if no parameters are given?

Using `v6.0.1`

**Comment by smaeda-ks** [comment]
@andrewbaxter Yes and No. If your Fastly account was created before `2021-02-01 00:00:00Z` then yes, `GET /services` returns all items if no parameters are given. Otherwise, pagination is always applied and you get partial data.

Therefore, we encourage you to use the `NewListServicesPaginator` function instead.
Example here: https://pkg.go.dev/github.com/fastly/go-fastly/v6/fastly#Client.NewListServicesPaginator

**Comment by andrewbaxter** [comment]
Okay thanks! That would be great to have in the documentation somewhere.
